### PR TITLE
Return all result pages from netbox GET requests

### PR DESCRIPTION
**Pull request by cpeel**
Netbox GET requests are returned in a paged format. Return *all* of the results from all pages and not just those from the first page.

### CODE REVIEW

**Comment by jagter** [comment]
Hi,

First of all, thank you for you're pull request. It is possible to use the limit as a kwarg. This option gives you the possibility to get all the records in one request. Did you encounter performance issues when using the limit option?

**Comment by cpeel** [comment]
Using `limit=0` worked.

I would suggest that be made the default in `NetboxConnection.get()`, otherwise it forces python-netbox users to know how the underlying Netbox API works and one of the goals of an SDK is to hide the underlying API implementation. For us it was obvious when only 50 of the 1050 devices were returned that something wasn't quite right, but I can see this being very confusing for someone with 51 devices.

**Comment by jagter** [comment]
Thank you for you're suggestion. I'll add the limit=0 to the get method. I agree with you're statement.

**Comment by cpeel** [comment]
Great - thank you!

**Pull request closed without merging**
