### PR TITLE
method get_ip_address created

### PR DESCRIPTION
**Pull request by forkd**
I added this method because sometimes it's useful to retrieve only one IP address.

### CODE REVIEW

**Comment by jagter** [comment]
Hi,

The get_ip_addresses method allows you to use arguments. So with this method it is also possible to get a single IP address.

I prefer the use of get_ip_addresses instead of new methods for single requests.

**Comment by forkd** [comment]
How can I get a single IP address using get_ip_addresses? Can you send me
an example?
Thanks.

**Comment by jagter** [comment]
An example:
print(netbox_con.ipam.get_ip_addresses(address='10.10.10.1/24'))

**Comment by forkd** [comment]
Thank you.
In this case, you can disconsider my pr.

**Pull request closed without merging**
